version: "3.8"

services:
  database:
    image: postgres:14-alpine # Use a lightweight Postgres image
    container_name: fiap_video_db
    restart: always
    environment:
      POSTGRES_USER: postgres # Change this
      POSTGRES_PASSWORD: postgres # Change this
      POSTGRES_DB: fiap_video_db # Change this
    ports:
      - "5432:5432" # Maps the container port to your machine
    volumes:
      - db-data:/var/lib/postgresql/data # Persists your database data

volumes:
  db-data:
